#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Secret_Files.Droid.Resource", IsApplication=true)]

namespace Secret_Files.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Secret_Files.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Secret_Files.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Secret_Files.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Secret_Files.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Secret_Files.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Secret_Files.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Secret_Files.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Secret_Files.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Secret_Files.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Secret_Files.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Secret_Files.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Secret_Files.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Secret_Files.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Secret_Files.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Secret_Files.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Secret_Files.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Secret_Files.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Secret_Files.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Secret_Files.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Secret_Files.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Secret_Files.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Secret_Files.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Secret_Files.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Secret_Files.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Secret_Files.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::FAB.Droid.Resource.Attribute.fab_colorDisabled = global::Secret_Files.Droid.Resource.Attribute.fab_colorDisabled;
			global::FAB.Droid.Resource.Attribute.fab_colorNormal = global::Secret_Files.Droid.Resource.Attribute.fab_colorNormal;
			global::FAB.Droid.Resource.Attribute.fab_colorPressed = global::Secret_Files.Droid.Resource.Attribute.fab_colorPressed;
			global::FAB.Droid.Resource.Attribute.fab_colorRipple = global::Secret_Files.Droid.Resource.Attribute.fab_colorRipple;
			global::FAB.Droid.Resource.Attribute.fab_shadow = global::Secret_Files.Droid.Resource.Attribute.fab_shadow;
			global::FAB.Droid.Resource.Attribute.fab_size = global::Secret_Files.Droid.Resource.Attribute.fab_size;
			global::FAB.Droid.Resource.Color.fab_material_blue_500 = global::Secret_Files.Droid.Resource.Color.fab_material_blue_500;
			global::FAB.Droid.Resource.Dimension.fab_elevation_lollipop = global::Secret_Files.Droid.Resource.Dimension.fab_elevation_lollipop;
			global::FAB.Droid.Resource.Dimension.fab_scroll_threshold = global::Secret_Files.Droid.Resource.Dimension.fab_scroll_threshold;
			global::FAB.Droid.Resource.Dimension.fab_shadow_size = global::Secret_Files.Droid.Resource.Dimension.fab_shadow_size;
			global::FAB.Droid.Resource.Dimension.fab_size_mini = global::Secret_Files.Droid.Resource.Dimension.fab_size_mini;
			global::FAB.Droid.Resource.Dimension.fab_size_normal = global::Secret_Files.Droid.Resource.Dimension.fab_size_normal;
			global::FAB.Droid.Resource.Drawable.fab_shadow = global::Secret_Files.Droid.Resource.Drawable.fab_shadow;
			global::FAB.Droid.Resource.Drawable.fab_shadow_mini = global::Secret_Files.Droid.Resource.Drawable.fab_shadow_mini;
			global::FAB.Droid.Resource.Id.mini = global::Secret_Files.Droid.Resource.Id.mini;
			global::FAB.Droid.Resource.Id.normal = global::Secret_Files.Droid.Resource.Id.normal;
			global::FAB.Droid.Resource.String.ApplicationName = global::Secret_Files.Droid.Resource.String.ApplicationName;
			global::FAB.Droid.Resource.String.Hello = global::Secret_Files.Droid.Resource.String.Hello;
			global::FAB.Droid.Resource.String.define_FloatingActionButton = global::Secret_Files.Droid.Resource.String.define_FloatingActionButton;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_author = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_author;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_authorWebsite = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_authorWebsite;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_isOpenSource = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_isOpenSource;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_libraryDescription = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_libraryDescription;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_libraryName = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_libraryName;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_libraryVersion = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_libraryVersion;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_libraryWebsite = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_libraryWebsite;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_licenseId = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_licenseId;
			global::FAB.Droid.Resource.String.library_FloatingActionButton_repositoryLink = global::Secret_Files.Droid.Resource.String.library_FloatingActionButton_repositoryLink;
			global::FAB.Droid.Resource.String.library_name = global::Secret_Files.Droid.Resource.String.library_name;
			global::FAB.Droid.Resource.Styleable.FloatingActionButton = global::Secret_Files.Droid.Resource.Styleable.FloatingActionButton;
			global::FAB.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::Secret_Files.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::FAB.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::Secret_Files.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::FAB.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::Secret_Files.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::FAB.Droid.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::Secret_Files.Droid.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::FAB.Droid.Resource.Styleable.FloatingActionButton_fab_shadow = global::Secret_Files.Droid.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::FAB.Droid.Resource.Styleable.FloatingActionButton_fab_size = global::Secret_Files.Droid.Resource.Styleable.FloatingActionButton_fab_size;
			global::Splat.Resource.String.library_name = global::Secret_Files.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::Secret_Files.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int ahBarColor = 2130771977;
			
			// aapt resource value: 0x7f010011
			public const int ahBarLength = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int ahBarWidth = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int ahCircleColor = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int ahDelayMillis = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int ahRadius = 2130771983;
			
			// aapt resource value: 0x7f01000a
			public const int ahRimColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int ahRimWidth = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int ahSpinSpeed = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int ahText = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int ahTextColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int ahTextSize = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int fab_colorDisabled = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int fab_colorNormal = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int fab_colorPressed = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fab_colorRipple = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fab_shadow = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fab_size = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int fab_material_blue_500 = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060004
			public const int fab_elevation_lollipop = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int fab_scroll_threshold = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int fab_shadow_size = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int fab_size_mini = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int fab_size_normal = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int brownhairblackcollarmale = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brownhairblackcollarmaleicon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int brownhaircaucasian = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int brownhaircaucasianicon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cameraplaceholder = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cameraplaceholder25x25 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cameraplaceholder28x28 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int fab_shadow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int fab_shadow_mini = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_add_a_photo_white_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_add_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_cake_amber_500_24dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_cake_blue_700_24dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_cake_deep_orange_700_24dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_cake_green_600_24dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_cake_pink_400_24dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_camera_alt_grey_500_24dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_camera_alt_white_24dp = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_clear_white_24dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_create_white_24dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_done_white_24dp = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_errorstatus = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_group_add_white_24dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_location_city_white_24dp = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_menu_white_24dp = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_party_mode_white_24dp = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_person_add_blue_500_24dp = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_person_add_light_blue_500_24dp = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_person_add_white_24dp = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_person_grey_500_24dp = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_person_pin_grey_500_24dp = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_phonelink_erase_grey_500_24dp = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_public_white_24dp = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_publish_white_24dp = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_refresh_white_24dp = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_school_white_24dp = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_search_white_24dp = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_send_white_24dp = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_sentiment_neutral_white_24dp = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_sentiment_very_dissatisfied_white_24dp = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_sentiment_very_satisfied_orange_500_24dp = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_sentiment_very_satisfied_white_24dp = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_settings_grey_500_24dp = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_share_purple_500_24dp = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_share_white_24dp = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_successstatus = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_thumb_down_white_24dp = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_thumb_up_white_24dp = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_trending_up_white_24dp = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_vpn_key_grey_500_24dp = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_whatshot_amber_500_24dp = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_whatshot_black_24dp = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_whatshot_orange_600_24dp = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_whatshot_red_dark_24dp = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_whatshot_white_24dp = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_whatshot_yellow_600_24dp = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_whatshot_yellow_light_24dp = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int icon = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int orangeeyes = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int orangeeyesicon = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int postsample = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int roundedbg = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int roundedbgdark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int SplashScreen = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int stormtrooper = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int stormtroopericon = 2130837569;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int loadingImage = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int loadingProgressBar = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int loadingProgressWheel = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int mini = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int normal = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int textViewStatus = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int ApplicationName = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Hello = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int define_FloatingActionButton = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int library_FloatingActionButton_author = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int library_FloatingActionButton_authorWebsite = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int library_FloatingActionButton_isOpenSource = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int library_FloatingActionButton_libraryDescription = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int library_FloatingActionButton_libraryName = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int library_FloatingActionButton_libraryVersion = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int library_FloatingActionButton_libraryWebsite = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int library_FloatingActionButton_licenseId = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int library_FloatingActionButton_repositoryLink = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int HideIcon = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_Splash = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] ProgressWheel = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
